server:
  port: 8090
spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
#          url-expression: "'lb:http://'+serviceId"
      routes:

        - id: READ_API
#          uri: lb://READ_API
          uri: http://localhost:8005/
          predicates:
            - Path=/api/product/**

        - id: gateway-service
#          uri: lb://gateway-service
          uri: http://localhost:8090
          predicates:
            - Path=/core/product/{id}?**
            - Method=GET
          filters:
            - StripPrefix=1

        - id: CORE_SERVICE
#          uri: lb://CORE_SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
